### ISSUE TITLE
Utils: Upgrade mistune to > 2.0.2

### ISSUE THREAD

**Issue by babyjunior56** [department-of-veterans-affairs/notification-utils#129]
### This should be worked in parallel with https://github.com/department-of-veterans-affairs/notification-api/issues/1383
Current version is v0.8.4, mistune is [currently up in the v3.x.x](https://pypi.org/project/mistune/).

- [x] Discussed with QA

## User Story

As a VANotify team member and client,
I want to remove vulnerabilities identified by Twistlock,
So that I am assured that the app is not subject to compromise.

## Engineering Checklist

- [ ] Upgrade mistune > 2.0.2 in setup.py

## Acceptance Criteria

- [ ] mistune is upgraded to 2.0.2 or greater

## Additional Info and Resources
- See this [ticket](https://app.zenhub.com/workspaces/va-notify-620d21369d810a00146ed9c8/issues/gh/department-of-veterans-affairs/vanotify-team/709).
- [Changelog](https://mistune.lepture.com/en/latest/changes.html)
  - NOTE: They do not have a changelog from before 3.x

**Comment by mjones-oddball** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/VA-Notify-620d21369d810a00146ed9c8/issues/department-of-veterans-affairs/notification-utils/129?planning-poker) with Zenhub @cris-oddball @EvanParish @justaskdavidb2 @k-macmillan @kalbfled @ldraney @nikolai-efimov

**Comment by cris-oddball** [comment]
Jupiter managed to upgrade to 2.0.2 using this PR to replace BlockGrammar and Inline Grammar. Should work the same for 3.x, but happily there is a migration guide for 2 > 3.

- [Jupiter's PR showing replacements](https://github.com/jupyter/nbconvert/pull/1764/files)
- [Mistune Upgrade guide from 2.x to 3.x](https://mistune.lepture.com/en/latest/upgrade.html)

@babyjunior56

**Comment by cris-oddball** [comment]
@kalbfled there is a migration guide for 2.x to 3.x, and I have linked it in an [above comment](https://github.com/department-of-veterans-affairs/notification-utils/issues/129#issuecomment-1655950909).

The security vulnerability is not present in mistunes 2.0.2, so upgrading to v3 is not a necessity, only if we need the features in 3.x.

**Comment by cris-oddball** [comment]
@babyjunior56  @EvanParish Just letting you know that there are two security concerns below 2.0.5

- [RegularExpression denial of service](https://security.snyk.io/package/pip/mistune/2.0.2) up to and including 2.0.2
- [CVE-2022-34749](https://nvd.nist.gov/vuln/detail/CVE-2022-34749) catastrophic backtracking; up to and including 2.0.2

So the minimum we should use is 2.0.5 (that is the current version)

**Comment by kalbfled** [comment]
The previous team [altered attributes](https://github.com/department-of-veterans-affairs/notification-utils/blob/master/notifications_utils/formatters.py#L26) on non-public package elements, including Mistune's [BlockGrammer class](https://github.com/lepture/mistune/blob/v1/mistune.py#L94), which is not present in mistune>=2.0.  That complicates this task significantly.

My understanding of the intended behavior is that Portal users enter markdown in the template editor.  When that template gets sent to API, the API uses notifications_utils to convert the markdown into HTML for previewing in a browser and for direct inclusion in HTML-enabled e-mails.  If we are willing to tolerate minor changes in formatting, that task could be much easier than the current implementation.

Judging by the existing unit tests, most of the code in formatter.py (the only file that imports mistune) is concerned with identifying and converting links.  templates.py uses formatter.py.

Using mistune 3.0.1:

The built-in "html" function converts properly formatted markdown links.
```python
>>> mistune.html("[https://www.google.com](https://www.google.com)")
'<p><a href="https://www.google.com">https://www.google.com</a></p>\n'
```

This doesn't work as intended with a link that is not marked-down.
```python
>>> mistune.html("https://www.google.com")
'<p>https://www.google.com</p>\n'
```

Rather than try to fix all the kludge in formatters.py, I would rather preprocess the template body with a regex that converts not-marked-down URLs to marked-down URLs and then just run mistune.html.  I would delete formatter.py and the associated unit tests and add additional tests as necessary for templates.py.

**Comment by kalbfled** [comment]
After a group discussion, we decided that we need a different plan of action and will open new tickets.

**Comment by mjones-oddball** [comment]
The changes/impacts are so great that we are looking at a rewrite and possible replacement of mistune. This is way larger than the expected scope. We looked at Canada/UK and they stayed at the lower version for the same reasons. We will need to sync with Strike team to come up with the best and safest approach as this impacts formatting of email template previews and sends.
